"use client";

import {FormEvent,useState} from "react";
import Link from "next/link";
import {api} from "../../../lib/api";

type Citation={policy_id:string;policy_title:string;section_id:string;section_heading:string;effective_date:string;excerpt:string};
type Answer={answer:string;confidence:"supported"|"partially_supported"|"insufficient_evidence";citations:Citation[];personal_facts:{label:string;value:string|number}[];suggested_action:{type:string;href:string}};
const examples=["Apakah saya perlu surat dokter untuk cuti sakit?","How many leave days do I have?","Siapa yang menyetujui cuti saya?"];

export default function AskTeamkuPage(){
  const [question,setQuestion]=useState(""); const [answer,setAnswer]=useState<Answer>(); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const ask=async(event:FormEvent)=>{event.preventDefault(); if(question.trim().length<3)return; setBusy(true);setError("");try{setAnswer(await api<Answer>("/policy-assistant/questions",{method:"POST",body:JSON.stringify({question:question.trim()})},localStorage.getItem("movon_user")||undefined));}catch(reason){setError(reason instanceof Error?reason.message:"Jawaban tidak dapat dimuat.");}finally{setBusy(false)}};
  return <section className="ask-teamku"><div className="page-heading"><div><p className="eyebrow">Company policy assistant</p><h1>Ask Teamku</h1><p>Jawaban hanya bersumber dari kebijakan perusahaan yang aktif. Untuk keputusan penting, konfirmasi ke HR.</p></div></div><article className="panel ask-form"><form onSubmit={ask}><label htmlFor="teamku-question">Apa yang ingin Anda tanyakan?</label><textarea id="teamku-question" rows={4} maxLength={800} value={question} onChange={event=>setQuestion(event.target.value)} placeholder="Contoh: Apakah saya perlu surat dokter untuk cuti sakit?"/><div className="ask-actions"><span>{question.length}/800</span><button className="primary-action auto-width" disabled={busy||question.trim().length<3}>{busy?"Mencari kebijakan…":"Tanya Teamku"}</button></div></form><div className="ask-examples">{examples.map(example=><button type="button" key={example} onClick={()=>setQuestion(example)}>{example}</button>)}</div></article>{error&&<article className="panel feature-empty compact"><h2>Belum dapat menjawab</h2><p>{error}</p><a className="secondary-button" href="mailto:hr@company.local">Hubungi HR</a></article>}{answer&&<article className="panel ask-answer"><div className="panel-head"><div><p className="eyebrow">Jawaban kebijakan</p><h2>{answer.confidence==="supported"?"Didukung kebijakan":"Perlu konfirmasi HR"}</h2></div><span className={`status ${answer.confidence==="supported"?"published":"draft"}`}>{answer.confidence.replace("_"," ")}</span></div><p className="ask-answer-copy">{answer.answer}</p>{answer.personal_facts.length>0&&<div className="ask-facts">{answer.personal_facts.map(item=><span key={item.label}><b>{item.label}</b> {item.value}</span>)}</div>}{answer.citations.length>0&&<details className="ask-citations" open><summary>Sumber kebijakan ({answer.citations.length})</summary>{answer.citations.map(item=><article key={`${item.policy_id}-${item.section_id}`}><b>{item.policy_title} · {item.section_heading}</b><small>Berlaku sejak {item.effective_date}</small><p>{item.excerpt}</p></article>)}</details>}<div className="ask-actions"><a className="secondary-button" href="mailto:hr@company.local">Hubungi HR</a>{answer.suggested_action.type!=="contact_hr"&&<Link className="primary-action auto-width" href={answer.suggested_action.href}>Buka tindakan terkait</Link>}</div></article>}</section>;
}
