"use client";

import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {api} from "../../../../lib/api";

type Policy={id:string;title:string;category:string;effective_date:string;state:string;updated_at:string};
const blank=()=>({title:"",category:"general",language:"id",effective_date:new Date().toISOString().slice(0,10),sections:[{heading:"",body:""}]});

export default function PolicySettings(){
  const router=useRouter(); const [items,setItems]=useState<Policy[]>([]); const [form,setForm]=useState(blank()); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const token=()=>localStorage.getItem("movon_user")||undefined;
  const load=()=>api<{items:Policy[]}>("/policies",{},token()).then(value=>setItems(value.items)).catch(()=>router.replace("/app/overview"));
  useEffect(()=>{api<{user:{role:string}}>("/me",{},token()).then(profile=>{if(profile.user.role!=="hr_admin")router.replace("/app/overview");else load();});},[router]);
  const save=async()=>{setBusy(true);try{await api("/policies",{method:"POST",body:JSON.stringify(form)},token());setForm(blank());setMessage("Draft kebijakan disimpan.");load();}catch(error){setMessage(error instanceof Error?error.message:"Tidak dapat menyimpan kebijakan.");}finally{setBusy(false)}};
  const publish=async(id:string)=>{if(!confirm("Publikasikan kebijakan ini?"))return;await api(`/policies/${id}/publish`,{method:"POST"},token());load()}; const archive=async(id:string)=>{if(!confirm("Batalkan publikasi dan arsipkan kebijakan ini?"))return;await api(`/policies/${id}/archive`,{method:"POST"},token());load()};
  return <><section className="page-heading"><div><p className="eyebrow">HR policy management</p><h1>Kebijakan perusahaan</h1><p>Draft tidak akan digunakan Ask Teamku sampai dipublikasikan.</p></div></section><section className="two-column-feature"><article className="panel request-form"><h2>Kebijakan baru</h2><label>Judul<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="form-grid"><label>Kategori<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Tanggal berlaku<input type="date" value={form.effective_date} onChange={e=>setForm({...form,effective_date:e.target.value})}/></label></div>{form.sections.map((section,index)=><div className="policy-section-editor" key={index}><label>Judul bagian<input value={section.heading} onChange={e=>setForm({...form,sections:form.sections.map((s,i)=>i===index?{...s,heading:e.target.value}:s)})}/></label><label>Isi kebijakan<textarea rows={5} value={section.body} onChange={e=>setForm({...form,sections:form.sections.map((s,i)=>i===index?{...s,body:e.target.value}:s)})}/></label></div>)}<button type="button" className="secondary-button" onClick={()=>setForm({...form,sections:[...form.sections,{heading:"",body:""}]})}>Tambah bagian</button><button className="primary-action" disabled={busy} onClick={save}>{busy?"Menyimpan…":"Simpan draft"}</button>{message&&<p className="field-error">{message}</p>}</article><article className="panel"><div className="panel-head"><div><p className="eyebrow">Published view</p><h2>Daftar kebijakan</h2></div></div>{items.length?items.map(item=><div className="request-item" key={item.id}><div><b>{item.title}</b><small>{item.category} · berlaku {item.effective_date}</small><span className={`status ${item.state}`}>{item.state}</span></div><div>{item.state==="draft"&&<button className="approve-button" onClick={()=>publish(item.id)}>Publikasikan</button>}{item.state==="published"&&<button className="danger-button" onClick={()=>archive(item.id)}>Batalkan publikasi</button>}</div></div>):<div className="feature-empty compact"><h2>Belum ada kebijakan</h2><p>Buat draft pertama untuk mulai menjawab pertanyaan karyawan.</p></div>}</article></section></>;
}
