"use client";
import {useEffect,useMemo,useState} from "react";
import {NotificationDialog,NotificationDialogState} from "../../../components/NotificationDialog";
import {api} from "../../../lib/api";

type Request={id:string;employee_name:string;department:string;start:string;end:string;days:number;reason:string;status:string;approver_comment?:string;calendar_sync_status?:string};
type Decision="approved"|"rejected"|"revision_requested";
const labels:Record<string,string>={pending:"Menunggu",approved:"Disetujui",rejected:"Ditolak",revision_requested:"Perlu revisi",cancelled:"Dibatalkan"};

export default function Approvals(){
  const [items,setItems]=useState<Request[]>([]),[filter,setFilter]=useState("pending"),[comment,setComment]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const [selected,setSelected]=useState<{request:Request;decision:Decision}|null>(null);
  const [notification,setNotification]=useState<NotificationDialogState|null>(null);
  const token=()=>localStorage.getItem("movon_user")||undefined;
  const notify=(type:NotificationDialogState["type"],title:string,message:string)=>setNotification({type,title,message});
  const load=()=>api<{items:Request[]}>("/approvals",{},token()).then(result=>{setItems(result.items);setError("")}).catch(reason=>notify("error","Tidak dapat memuat persetujuan",reason instanceof Error?reason.message:"Data persetujuan gagal dimuat."));
  useEffect(()=>{load()},[]);
  const visible=useMemo(()=>filter==="all"?items:items.filter(item=>item.status===filter),[items,filter]);
  const count=(status:string)=>items.filter(item=>item.status===status).length;
  const open=(request:Request,decision:Decision)=>{setSelected({request,decision});setComment(decision==="approved"?"Disetujui sesuai kebijakan dan saldo cuti.":"");setError("")};
  async function submitDecision(){if(!selected)return;if(comment.trim().length<3){setError("Komentar keputusan minimal 3 karakter.");return}setBusy(true);try{const result=await api<Request>(`/approvals/${selected.request.id}`,{method:"POST",body:JSON.stringify({decision:selected.decision,comment})},token());notify("success","Keputusan tersimpan",result.calendar_sync_status==="failed"?`Permohonan diproses, tetapi event Google Calendar gagal dibuat.`:`Permohonan ${selected.request.employee_name} berhasil diproses.`);setSelected(null);setComment("");await load()}catch(reason){notify("error","Keputusan gagal disimpan",reason instanceof Error?reason.message:"Keputusan gagal disimpan")}finally{setBusy(false)}}
  return <><section className="page-heading"><div><p className="eyebrow">Approval inbox</p><h1>Persetujuan</h1><p>Tinjau permohonan tim sesuai cakupan dan simpan keputusan dengan catatan.</p></div><button className="secondary-button" onClick={load}>Perbarui data</button></section><div className="filter-tabs" role="tablist">{[["pending","Menunggu"],["approved","Disetujui"],["rejected","Ditolak"],["all","Semua"]].map(([key,label])=><button role="tab" aria-selected={filter===key} className={filter===key?"active":""} onClick={()=>setFilter(key)} key={key}>{label}<span>{key==="all"?items.length:count(key)}</span></button>)}</div><div className="card table-card"><div className="table-wrap"><table className="table"><thead><tr><th>Karyawan</th><th>Jenis</th><th>Tanggal</th><th>Durasi</th><th>Alasan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{visible.map(item=><tr key={item.id}><td><b>{item.employee_name}</b><small>{item.department}</small></td><td>Cuti tahunan</td><td>{formatDate(item.start)} — {formatDate(item.end)}</td><td>{item.days} hari kerja</td><td>{item.reason}{item.approver_comment&&<small>Catatan: {item.approver_comment}</small>}</td><td><span className={`status ${item.status}`}>{labels[item.status]||item.status}</span></td><td>{item.status==="pending"?<div className="approval-actions"><button className="approve-button" onClick={()=>open(item,"approved")}>Setujui</button><button className="reject-button" onClick={()=>open(item,"rejected")}>Tolak</button></div>:<span className="muted">Selesai</span>}</td></tr>)}</tbody></table></div>{visible.length===0&&<div className="feature-empty"><span>✓</span><h2>Tidak ada permohonan di sini</h2><p>Semua permohonan pada status ini sudah tertangani.</p></div>}</div>{selected&&<div className="dialog-backdrop" role="presentation"><section className="decision-dialog" role="dialog" aria-modal="true" aria-labelledby="decision-title"><p className="eyebrow">Konfirmasi keputusan</p><h2 id="decision-title">{selected.decision==="approved"?"Setujui":"Tolak"} permohonan {selected.request.employee_name}?</h2><p>{formatDate(selected.request.start)} — {formatDate(selected.request.end)} · {selected.request.days} hari kerja</p><label>Catatan keputusan<textarea autoFocus rows={4} value={comment} onChange={event=>setComment(event.target.value)} placeholder="Jelaskan keputusan untuk karyawan"/></label>{error&&<p className="field-error">{error}</p>}<div className="dialog-actions"><button className="secondary-button" onClick={()=>{setSelected(null);setError("")}}>Batal</button><button className={selected.decision==="approved"?"approve-button":"danger-button"} disabled={busy} onClick={submitDecision}>{busy?"Menyimpan…":"Simpan keputusan"}</button></div></section></div>}<NotificationDialog notification={notification} onClose={()=>setNotification(null)}/></>;
}
function formatDate(value:string){return new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value}T00:00:00`))}
